/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fhx;

import firehistory.*;

import java.util.ArrayList;
import java.util.List;
import firehistory.*;
import javax.swing.JFileChooser;
import java.io.File;

/**
 *
 * @author andreskis
 */
public class mainFrame extends javax.swing.JFrame {
    private int indexOfNewTab = 1;
    private PnlHome homePanel;
    private PnlGeneral pnlGeneral;
    private List<FireHistory> f;
   // private FireHistory fireHist;

    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        
        pnlWelcome.removeAll();
        homePanel = new PnlHome();
        pnlWelcome.add(homePanel);
        homePanel.setSize(530, 200);
        homePanel.setVisible(true);
        pnlWelcome.revalidate();
        pnlWelcome.repaint();

        pnlNew.removeAll();
        pnlGeneral = new PnlGeneral(this);
        pnlNew.add(pnlGeneral);
        pnlGeneral.setSize(500, 500);
        pnlGeneral.setVisible(true);
        pnlNew.revalidate();
        pnlNew.repaint();
        
        f = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();
        pnlWelcome = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        pnlNew = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));

        pnlWelcome.setPreferredSize(new java.awt.Dimension(980, 500));
        pnlWelcome.setRequestFocusEnabled(false);

        jTextPane2.setEditable(false);
        jTextPane2.setText("Directions on how to use our software will be added here!!\n\n\nTo create a new sample select \"File->New Sample\"");
        jScrollPane3.setViewportView(jTextPane2);

        javax.swing.GroupLayout pnlWelcomeLayout = new javax.swing.GroupLayout(pnlWelcome);
        pnlWelcome.setLayout(pnlWelcomeLayout);
        pnlWelcomeLayout.setHorizontalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(283, Short.MAX_VALUE))
        );
        pnlWelcomeLayout.setVerticalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        tabs.addTab("Welcome", pnlWelcome);

        javax.swing.GroupLayout pnlNewLayout = new javax.swing.GroupLayout(pnlNew);
        pnlNew.setLayout(pnlNewLayout);
        pnlNewLayout.setHorizontalGroup(
            pnlNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
        );
        pnlNewLayout.setVerticalGroup(
            pnlNewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        tabs.addTab("New", pnlNew);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("New Sample");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Save All");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Export File");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Import File");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //TODO Check to save file
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.tabs.setSelectedIndex(indexOfNewTab);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        if (fileChooser.showOpenDialog(jMenu1) == JFileChooser.APPROVE_OPTION)
        {
            FireHistory fireHistory = new FireHistory(fileChooser.getSelectedFile().getAbsolutePath());
            addFireHistoryTab(fireHistory);
        }
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        int position = tabs.getSelectedIndex();
        
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showSaveDialog(jMenu1) == JFileChooser.APPROVE_OPTION)
        {
            ((PnlFile)tabs.getTabComponentAt(position)).saveFireHistory();
            //fireHist.SaveFile(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

//   /**
//    @param args the command line arguments
//    */
//   public static void main(String args[])
//   {
//      /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//       */
//      try
//      {
//         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//         {
//            if ("Nimbus".equals(info.getName()))
//            {
//               javax.swing.UIManager.setLookAndFeel(info.getClassName());
//               break;
//            }
//         }
//      }
//      catch (ClassNotFoundException ex)
//      {
//         java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      }
//      catch (InstantiationException ex)
//      {
//         java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      }
//      catch (IllegalAccessException ex)
//      {
//         java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      }
//      catch (javax.swing.UnsupportedLookAndFeelException ex)
//      {
//         java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//      }
//        //</editor-fold>
//
//      /* Create and display the form */
//      java.awt.EventQueue.invokeLater(new Runnable()
//      {
//         public void run()
//         {
//            
//            new mainFrame().setVisible(true);
//            
//         }
//      });
//   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNew;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
//
//    private void addPanel(String title, FireHistory fireHistory) {
//        f.add(fireHistory);
//        int index = f.indexOf(fireHistory);
//        tabs.remove(indexOfNewTab);
//        PnlFile tmp = new PnlFile(f.get(index));
//        files.add(tmp);
//        tabs.addTab(title, tmp);
//        //Icon icon = new MetalIconFactory.PaletteCloseIcon();
//        //tabs.insertTab(title, icon, tmp, title, indexOfNewTab);
//        tabs.add("New", pnlNew);
//        indexOfNewTab++;
//        
//    }
    
    public void addFireHistoryTab(FireHistory fireHistory){
        tabs.remove(indexOfNewTab);
        PnlFile tmp = new PnlFile(fireHistory);
        tabs.addTab(fireHistory.getName_of_site(), tmp);
        tabs.add("New", pnlNew);
        indexOfNewTab++;
        tabs.setSelectedIndex(indexOfNewTab);
    }

}
