/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fhx;
import firehistory.*;

/**

 @author gerhardyz
 */
public class PnlEditSiteInfo extends javax.swing.JPanel
{

   private FireHistory f;
   private Series s;
   /**
    Creates new form pnl_wiz_start
    */
   public PnlEditSiteInfo(FireHistory inF, Series inS)
   {
      initComponents();
      f = inF;
      s = inS;
   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jPanel1 = new javax.swing.JPanel();
      jLabel8 = new javax.swing.JLabel();
      jLabel9 = new javax.swing.JLabel();
      jTextField4 = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      jTextField3 = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jTextField2 = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jTextField1 = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      jTextField5 = new javax.swing.JTextField();
      jLabel11 = new javax.swing.JLabel();
      jLabel12 = new javax.swing.JLabel();
      jTextField6 = new javax.swing.JTextField();
      jLabel13 = new javax.swing.JLabel();
      jLabel28 = new javax.swing.JLabel();
      jTextField14 = new javax.swing.JTextField();
      jLabel29 = new javax.swing.JLabel();
      jLabel30 = new javax.swing.JLabel();
      jTextField15 = new javax.swing.JTextField();
      jLabel31 = new javax.swing.JLabel();
      jLabel32 = new javax.swing.JLabel();
      jTextField16 = new javax.swing.JTextField();
      jLabel33 = new javax.swing.JLabel();
      jTextField26 = new javax.swing.JTextField();
      jLabel52 = new javax.swing.JLabel();
      jLabel53 = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      jLabel14 = new javax.swing.JLabel();
      jTextField7 = new javax.swing.JTextField();
      jLabel15 = new javax.swing.JLabel();
      jLabel16 = new javax.swing.JLabel();
      jTextField8 = new javax.swing.JTextField();
      jLabel17 = new javax.swing.JLabel();
      jLabel18 = new javax.swing.JLabel();
      jTextField9 = new javax.swing.JTextField();
      jLabel19 = new javax.swing.JLabel();
      jLabel20 = new javax.swing.JLabel();
      jTextField10 = new javax.swing.JTextField();
      jLabel21 = new javax.swing.JLabel();
      jLabel22 = new javax.swing.JLabel();
      jTextField11 = new javax.swing.JTextField();
      jLabel23 = new javax.swing.JLabel();
      jLabel34 = new javax.swing.JLabel();
      jTextField17 = new javax.swing.JTextField();
      jLabel35 = new javax.swing.JLabel();
      jLabel36 = new javax.swing.JLabel();
      jTextField18 = new javax.swing.JTextField();
      jLabel37 = new javax.swing.JLabel();
      jLabel38 = new javax.swing.JLabel();
      jTextField19 = new javax.swing.JTextField();
      jLabel39 = new javax.swing.JLabel();
      jLabel40 = new javax.swing.JLabel();
      jTextField20 = new javax.swing.JTextField();
      jLabel41 = new javax.swing.JLabel();
      jLabel26 = new javax.swing.JLabel();
      jTextField13 = new javax.swing.JTextField();
      jLabel27 = new javax.swing.JLabel();
      jPanel3 = new javax.swing.JPanel();
      jLabel42 = new javax.swing.JLabel();
      jTextField21 = new javax.swing.JTextField();
      jLabel43 = new javax.swing.JLabel();
      jLabel44 = new javax.swing.JLabel();
      jTextField22 = new javax.swing.JTextField();
      jLabel45 = new javax.swing.JLabel();
      jLabel46 = new javax.swing.JLabel();
      jTextField23 = new javax.swing.JTextField();
      jLabel47 = new javax.swing.JLabel();
      jLabel48 = new javax.swing.JLabel();
      jTextField24 = new javax.swing.JTextField();
      jLabel49 = new javax.swing.JLabel();
      jLabel50 = new javax.swing.JLabel();
      jTextField25 = new javax.swing.JTextField();
      jLabel51 = new javax.swing.JLabel();
      jLabel54 = new javax.swing.JLabel();
      jTextField27 = new javax.swing.JTextField();
      jLabel55 = new javax.swing.JLabel();
      jLabel56 = new javax.swing.JLabel();
      jTextField28 = new javax.swing.JTextField();
      jLabel57 = new javax.swing.JLabel();
      jLabel58 = new javax.swing.JLabel();
      jTextField29 = new javax.swing.JTextField();
      jLabel59 = new javax.swing.JLabel();
      jLabel60 = new javax.swing.JLabel();
      jTextField30 = new javax.swing.JTextField();
      jLabel61 = new javax.swing.JLabel();
      jLabel24 = new javax.swing.JLabel();
      jTextField12 = new javax.swing.JTextField();
      jLabel25 = new javax.swing.JLabel();

      setPreferredSize(new java.awt.Dimension(850, 450));

      jLabel8.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel8.setText("Max 70 Characters");

      jLabel9.setText("Collectors:");

      jTextField4.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField4ActionPerformed(evt);
         }
      });

      jLabel7.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel7.setText("Max 20 Characters");

      jLabel6.setText("Collection Date:");

      jLabel5.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel5.setText("Max 3 Characters");

      jTextField2.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField2ActionPerformed(evt);
         }
      });

      jLabel3.setText("Site Code:");

      jLabel4.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel4.setText("Max 70 Characters");

      jTextField1.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField1ActionPerformed(evt);
         }
      });

      jLabel2.setText("Name of Site:");

      jLabel10.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel10.setText("Max 70 Characters");

      jTextField5.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField5ActionPerformed(evt);
         }
      });

      jLabel11.setText("Crossdaters:");

      jLabel12.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel12.setText("Max 70 Characters");

      jTextField6.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField6ActionPerformed(evt);
         }
      });

      jLabel13.setText("Number samples:");

      jLabel28.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel28.setText("Max 70 Characters");

      jTextField14.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField14ActionPerformed(evt);
         }
      });

      jLabel29.setText("Country:");

      jLabel30.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel30.setText("Max 70 Characters");

      jTextField15.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField15ActionPerformed(evt);
         }
      });

      jLabel31.setText("Habitat type:");

      jLabel32.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel32.setText("Max 70 Characters");

      jTextField16.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField16ActionPerformed(evt);
         }
      });

      jLabel33.setText("Common name:");

      jTextField26.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField26ActionPerformed(evt);
         }
      });

      jLabel52.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel52.setText("Max 70 Characters");

      jLabel53.setText("Species name:");

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel5)
                           .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                           .addComponent(jLabel4)))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jLabel7)
                           .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                           .addComponent(jLabel8)))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                           .addComponent(jLabel10)))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                           .addComponent(jLabel12)))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jTextField26, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                           .addComponent(jLabel52)))))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addGap(0, 0, Short.MAX_VALUE)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jTextField16, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                           .addComponent(jLabel32)))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jTextField15, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                           .addComponent(jLabel30)))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(jTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                           .addComponent(jLabel28))))))
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel9)
               .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel11)
               .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel10)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel13)
               .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel12)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel53)
               .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel52)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel33)
               .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel32)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel31)
               .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel30)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel29)
               .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel28)
            .addContainerGap(22, Short.MAX_VALUE))
      );

      jTextField1.getAccessibleContext().setAccessibleDescription("");

      jLabel14.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel14.setText("Max 70 Characters");

      jTextField7.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField7ActionPerformed(evt);
         }
      });

      jLabel15.setText("County:");

      jLabel16.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel16.setText("Max 70 Characters");

      jTextField8.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField8ActionPerformed(evt);
         }
      });

      jLabel17.setText("Park/Monument:");

      jLabel18.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel18.setText("Max 70 Characters");

      jTextField9.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField9ActionPerformed(evt);
         }
      });

      jLabel19.setText("National Forest:");

      jLabel20.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel20.setText("Max 70 Characters");

      jTextField10.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField10ActionPerformed(evt);
         }
      });

      jLabel21.setText("Ranger district:");

      jLabel22.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel22.setText("Max 70 Characters");

      jTextField11.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField11ActionPerformed(evt);
         }
      });

      jLabel23.setText("Township:");

      jLabel34.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel34.setText("Max 70 Characters");

      jTextField17.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField17ActionPerformed(evt);
         }
      });

      jLabel35.setText("UTM easting:");

      jLabel36.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel36.setText("Max 70 Characters");

      jTextField18.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField18ActionPerformed(evt);
         }
      });

      jLabel37.setText("Quarter section:");

      jLabel38.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel38.setText("Max 70 Characters");

      jTextField19.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField19ActionPerformed(evt);
         }
      });

      jLabel39.setText("Section:");

      jLabel40.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel40.setText("Max 70 Characters");

      jTextField20.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField20ActionPerformed(evt);
         }
      });

      jLabel41.setText("Range:");

      jLabel26.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel26.setText("Max 70 Characters");

      jTextField13.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField13ActionPerformed(evt);
         }
      });

      jLabel27.setText("State:");

      javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
      jPanel2.setLayout(jPanel2Layout);
      jPanel2Layout.setHorizontalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel27)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel26)))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel15)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel14)))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel17)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel16)))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel19)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel18)))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel21)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel20)))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel23)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel22)))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel41)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField20, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel40)))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel39)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField19, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel38)))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel37)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField18, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel36)))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                  .addComponent(jLabel35)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField17, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel34))))
            .addContainerGap())
      );
      jPanel2Layout.setVerticalGroup(
         jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel27)
               .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel26)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel15)
               .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel14)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel17)
               .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel16)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel19)
               .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel18)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel21)
               .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel20)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel23)
               .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel22)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel41)
               .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel40)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel39)
               .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel38)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel37)
               .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel36)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel35)
               .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel34)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      jLabel42.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel42.setText("Max 70 Characters");

      jTextField21.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField21ActionPerformed(evt);
         }
      });

      jLabel43.setText("Latitude:");

      jLabel44.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel44.setText("Max 70 Characters");

      jTextField22.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField22ActionPerformed(evt);
         }
      });

      jLabel45.setText("Longitude:");

      jLabel46.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel46.setText("Max 70 Characters");

      jTextField23.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField23ActionPerformed(evt);
         }
      });

      jLabel47.setText("Topographic map:");

      jLabel48.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel48.setText("Max 70 Characters");

      jTextField24.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField24ActionPerformed(evt);
         }
      });

      jLabel49.setText("Lowest elev:");

      jLabel50.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel50.setText("Max 70 Characters");

      jTextField25.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField25ActionPerformed(evt);
         }
      });

      jLabel51.setText("Highest elev:");

      jLabel54.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel54.setText("Max 70 Characters");

      jTextField27.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField27ActionPerformed(evt);
         }
      });

      jLabel55.setText("Substrate type:");

      jLabel56.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel56.setText("Max 70 Characters");

      jTextField28.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField28ActionPerformed(evt);
         }
      });

      jLabel57.setText("Area sampled:");

      jLabel58.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel58.setText("Max 70 Characters");

      jTextField29.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField29ActionPerformed(evt);
         }
      });

      jLabel59.setText("Aspect:");

      jLabel60.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel60.setText("Max 70 Characters");

      jTextField30.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField30ActionPerformed(evt);
         }
      });

      jLabel61.setText("Slope:");

      jLabel24.setFont(new java.awt.Font("Tahoma", 2, 8)); // NOI18N
      jLabel24.setText("Max 70 Characters");

      jTextField12.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            jTextField12ActionPerformed(evt);
         }
      });

      jLabel25.setText("UTM northing:");

      javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
      jPanel3.setLayout(jPanel3Layout);
      jPanel3Layout.setHorizontalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(jLabel43)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField21, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel42)))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(jLabel25)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel24)))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(jLabel45)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField22, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel44)))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(jLabel47)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField23, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel46)))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(jLabel49)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField24, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel48)))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(jLabel51)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField25, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel50)))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(jLabel61)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField30, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel60)))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(jLabel59)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField29, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel58)))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(jLabel57)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField28, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel56)))
               .addGroup(jPanel3Layout.createSequentialGroup()
                  .addComponent(jLabel55)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jTextField27, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                     .addComponent(jLabel54))))
            .addContainerGap(20, Short.MAX_VALUE))
      );
      jPanel3Layout.setVerticalGroup(
         jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel25)
               .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel24)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel43)
               .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel42)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel45)
               .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel44)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel47)
               .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel46)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel49)
               .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel48)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel51)
               .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel50)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel61)
               .addComponent(jTextField30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel60)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel59)
               .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel58)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel57)
               .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel56)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel55)
               .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel54)
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(12, 12, 12))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
   }// </editor-fold>//GEN-END:initComponents

   private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
   {//GEN-HEADEREND:event_jTextField1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField1ActionPerformed

   private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField2ActionPerformed
   {//GEN-HEADEREND:event_jTextField2ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField2ActionPerformed

   private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField4ActionPerformed
   {//GEN-HEADEREND:event_jTextField4ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField4ActionPerformed

   private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField5ActionPerformed
   {//GEN-HEADEREND:event_jTextField5ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField5ActionPerformed

   private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField6ActionPerformed
   {//GEN-HEADEREND:event_jTextField6ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField6ActionPerformed

   private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField7ActionPerformed
   {//GEN-HEADEREND:event_jTextField7ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField7ActionPerformed

   private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField8ActionPerformed
   {//GEN-HEADEREND:event_jTextField8ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField8ActionPerformed

   private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField9ActionPerformed
   {//GEN-HEADEREND:event_jTextField9ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField9ActionPerformed

   private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField10ActionPerformed
   {//GEN-HEADEREND:event_jTextField10ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField10ActionPerformed

   private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField11ActionPerformed
   {//GEN-HEADEREND:event_jTextField11ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField11ActionPerformed

   private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField12ActionPerformed
   {//GEN-HEADEREND:event_jTextField12ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField12ActionPerformed

   private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField13ActionPerformed
   {//GEN-HEADEREND:event_jTextField13ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField13ActionPerformed

   private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField14ActionPerformed
   {//GEN-HEADEREND:event_jTextField14ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField14ActionPerformed

   private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField15ActionPerformed
   {//GEN-HEADEREND:event_jTextField15ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField15ActionPerformed

   private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField16ActionPerformed
   {//GEN-HEADEREND:event_jTextField16ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField16ActionPerformed

   private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField17ActionPerformed
   {//GEN-HEADEREND:event_jTextField17ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField17ActionPerformed

   private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField18ActionPerformed
   {//GEN-HEADEREND:event_jTextField18ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField18ActionPerformed

   private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField19ActionPerformed
   {//GEN-HEADEREND:event_jTextField19ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField19ActionPerformed

   private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField20ActionPerformed
   {//GEN-HEADEREND:event_jTextField20ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField20ActionPerformed

   private void jTextField30ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField30ActionPerformed
   {//GEN-HEADEREND:event_jTextField30ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField30ActionPerformed

   private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField29ActionPerformed
   {//GEN-HEADEREND:event_jTextField29ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField29ActionPerformed

   private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField28ActionPerformed
   {//GEN-HEADEREND:event_jTextField28ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField28ActionPerformed

   private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField27ActionPerformed
   {//GEN-HEADEREND:event_jTextField27ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField27ActionPerformed

   private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField25ActionPerformed
   {//GEN-HEADEREND:event_jTextField25ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField25ActionPerformed

   private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField24ActionPerformed
   {//GEN-HEADEREND:event_jTextField24ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField24ActionPerformed

   private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField23ActionPerformed
   {//GEN-HEADEREND:event_jTextField23ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField23ActionPerformed

   private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField22ActionPerformed
   {//GEN-HEADEREND:event_jTextField22ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField22ActionPerformed

   private void jTextField21ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField21ActionPerformed
   {//GEN-HEADEREND:event_jTextField21ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField21ActionPerformed

   private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField26ActionPerformed
   {//GEN-HEADEREND:event_jTextField26ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_jTextField26ActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel16;
   private javax.swing.JLabel jLabel17;
   private javax.swing.JLabel jLabel18;
   private javax.swing.JLabel jLabel19;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel20;
   private javax.swing.JLabel jLabel21;
   private javax.swing.JLabel jLabel22;
   private javax.swing.JLabel jLabel23;
   private javax.swing.JLabel jLabel24;
   private javax.swing.JLabel jLabel25;
   private javax.swing.JLabel jLabel26;
   private javax.swing.JLabel jLabel27;
   private javax.swing.JLabel jLabel28;
   private javax.swing.JLabel jLabel29;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel30;
   private javax.swing.JLabel jLabel31;
   private javax.swing.JLabel jLabel32;
   private javax.swing.JLabel jLabel33;
   private javax.swing.JLabel jLabel34;
   private javax.swing.JLabel jLabel35;
   private javax.swing.JLabel jLabel36;
   private javax.swing.JLabel jLabel37;
   private javax.swing.JLabel jLabel38;
   private javax.swing.JLabel jLabel39;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel40;
   private javax.swing.JLabel jLabel41;
   private javax.swing.JLabel jLabel42;
   private javax.swing.JLabel jLabel43;
   private javax.swing.JLabel jLabel44;
   private javax.swing.JLabel jLabel45;
   private javax.swing.JLabel jLabel46;
   private javax.swing.JLabel jLabel47;
   private javax.swing.JLabel jLabel48;
   private javax.swing.JLabel jLabel49;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel50;
   private javax.swing.JLabel jLabel51;
   private javax.swing.JLabel jLabel52;
   private javax.swing.JLabel jLabel53;
   private javax.swing.JLabel jLabel54;
   private javax.swing.JLabel jLabel55;
   private javax.swing.JLabel jLabel56;
   private javax.swing.JLabel jLabel57;
   private javax.swing.JLabel jLabel58;
   private javax.swing.JLabel jLabel59;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel60;
   private javax.swing.JLabel jLabel61;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JPanel jPanel3;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField10;
   private javax.swing.JTextField jTextField11;
   private javax.swing.JTextField jTextField12;
   private javax.swing.JTextField jTextField13;
   private javax.swing.JTextField jTextField14;
   private javax.swing.JTextField jTextField15;
   private javax.swing.JTextField jTextField16;
   private javax.swing.JTextField jTextField17;
   private javax.swing.JTextField jTextField18;
   private javax.swing.JTextField jTextField19;
   private javax.swing.JTextField jTextField2;
   private javax.swing.JTextField jTextField20;
   private javax.swing.JTextField jTextField21;
   private javax.swing.JTextField jTextField22;
   private javax.swing.JTextField jTextField23;
   private javax.swing.JTextField jTextField24;
   private javax.swing.JTextField jTextField25;
   private javax.swing.JTextField jTextField26;
   private javax.swing.JTextField jTextField27;
   private javax.swing.JTextField jTextField28;
   private javax.swing.JTextField jTextField29;
   private javax.swing.JTextField jTextField3;
   private javax.swing.JTextField jTextField30;
   private javax.swing.JTextField jTextField4;
   private javax.swing.JTextField jTextField5;
   private javax.swing.JTextField jTextField6;
   private javax.swing.JTextField jTextField7;
   private javax.swing.JTextField jTextField8;
   private javax.swing.JTextField jTextField9;
   // End of variables declaration//GEN-END:variables
}
